### 회원가입
POST {{url}}/accounts/sign-up
Content-Type: application/json
Accept: application/json

{
  "username": "testtest",
  "password": "testtest"
}

### 로그인
POST {{url}}/accounts/sign-in
Content-Type: application/json
Accept: application/json

{
  "username": "testtest",
  "password": "testtest"
}

> {%
 client.global.set("Authorization", response.headers.valueOf("Authorization"));
 client.log(client.global.get("Authorization"));
 %}

### API Change
PUT {{url}}/key
Authorization: {{Authorization}}
Content-Type: application/json

{
  "key": "RGAPI-f01903e1-3e6c-47f1-8061-5f8011a09988"
}

### 프로필 생성
POST {{url}}/profiles
Authorization: {{Authorization}}
Content-Type: application/json

{
  "summonerName": "Mastery7",
  "preferChampions": [
    {
      "priority": 1,
      "championId": 76
    },
    {
      "priority": 2,
      "championId": 11
    }
  ],
  "preferLines": [
    {
      "priority": 1,
      "line": "TOP"
    },
    {
      "priority": 2,
      "line": "AD"
    }
  ],
  "preferQueue" : "NONE"
}

### 프로필 인증
PATCH {{url}}/profiles/auth
Authorization: {{Authorization}}
Content-Type: application/json

{
  "summonerId": "YLhKPSvcrbAGV4_oiKMtLZLlAC7dITaXxBUtxkStn9qHqGU"
}

### 프로필 인증확인
PATCH {{url}}/profiles/auth-confirm
Authorization: {{Authorization}}
Content-Type: application/json

{
  "summonerId": "YLhKPSvcrbAGV4_oiKMtLZLlAC7dITaXxBUtxkStn9qHqGU"
}

### 프로필 조회
GET {{url}}/profiles
Authorization: {{Authorization}}