### 회원가입
POST {{serverUrl}}/accounts/sign-up
Content-Type: application/json
Accept: application/json

{
  "username": "test1111",
  "password": "test1111"
}

### 로그인
POST {{serverUrl}}/accounts/sign-in
Content-Type: application/json
Accept: application/json

{
  "username": "test1111",
  "password": "test1111"
}

> {%
 client.global.set("Authorization", response.headers.valueOf("Authorization"));
 client.log(client.global.get("Authorization"));
 %}

### API Change
PUT {{serverUrl}}/key
Authorization: {{Authorization}}
Content-Type: application/json

{
  "key": "RGAPI-747fd70f-b235-45fa-8a2e-d6c3fec5f028"
}

### 프로필 생성
POST {{serverUrl}}/profiles
Authorization: {{Authorization}}
Content-Type: application/json

{
  "summonerName": "mastery7",
  "description": "저는 테스터입니다. 칼챔을 좋아하며 스플릿 위주입니다.",
  "preferKeywords": [
    "HEADSMAN", "SPLIT"
  ],
  "preferChampions": [
    {
      "priority": 1,
      "championId": 5
    },
    {
      "priority": 2,
      "championId": 6
    },
    {
      "priority": 3,
      "championId": 7
    }
  ],
  "preferLines": [
    {
      "priority": 1,
      "line": "SUP"
    },
    {
      "priority": 2,
      "line": "TOP"
    }
  ],
  "preferQueue" : "RANKED_SOLO"
}

### 프로필 인증
PATCH {{serverUrl}}/profiles/auth
Authorization: {{Authorization}}
Content-Type: application/json

{
  "summonerId": "8eDN8njLDjyiT9H8_SZFOi2Ft17wr3oDXsNnc8iDiz77lJzybOTih8Uy4w"
}

### 프로필 인증확인
PATCH {{serverUrl}}/profiles/auth-confirm
Authorization: {{Authorization}}
Content-Type: application/json

{
  "summonerId": "8eDN8njLDjyiT9H8_SZFOi2Ft17wr3oDXsNnc8iDiz77lJzybOTih8Uy4w"
}

### 프로필 조회
GET {{serverUrl}}/profiles
Authorization: {{Authorization}}

### 프로필 조회 - 검색
GET {{serverUrl}}/profiles?summonerName=hideonbush
Authorization: {{Authorization}}

### 프로필 인증을 위한 조회 - 검색
GET {{serverUrl}}/summoner?summonerName=hideonbush
Authorization: {{Authorization}}

### 프로필 상세조회
GET {{serverUrl}}/profiles/8
Authorization: {{Authorization}}

### 프로필 수정
PATCH {{serverUrl}}/profiles/8
Authorization: {{Authorization}}
Content-Type: application/json

{
  "summonerName": "강친밥",
  "description": "저는 미드라이너입니다. 로밍다니는것을 좋아하며 즐겜유저입니다.",
  "preferKeywords": [
    "GANKING", "ORIENTED_OBJECT"
  ],
  "preferChampions": [
    {
      "priority": 3,
      "championId": 11
    },
    {
      "priority": 1,
      "championId": 22
    },
    {
      "priority": 2,
      "championId": 33
    }
  ],
  "preferLines": [
    {
      "priority": 2,
      "line": "AD"
    },
    {
      "priority": 1,
      "line": "TOP"
    }
  ],
  "preferQueue" : "RANKED_SOLO"
}


### 프로필 삭제
DELETE {{serverUrl}}/profiles/7
Authorization: {{Authorization}}