name: G-Makers-server-CI

env:
  DB_DATABASE: ${{ secrets.MYSQL_DATABASE }}
  DB_USER: ${{ secrets.MYSQL_USERNAME }}
  DB_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Setup MySQL
      - uses: mirromutth/mysql-action@v1.1
        with:
          container port: 3306
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql version: '8.0'
          mysql database: ${{ secrets.MYSQL_DATABASE }}
          mysql user: ${{ secrets.MYSQL_USERNAME }}
          mysql password: ${{ secrets.MYSQL_PASSWORD }}
#        run: |
#          sudo /etc/init.d/mysql start
#          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v2

      - name : Set up JDK 11
        uses: actions/setup-java@v1
        with:
          distribution: 'adopt'
          java-version: '11'

      - name : Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name : Build with Gradle
        run: ./gradlew clean build
        shell: bash

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_TAG }}

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Show Current Time
        run: echo "CurrentTime=${{steps.current-time.outputs.formattedTime}}"
        shell: bash
